# Generated by Django 6.1.1 on 2026-09-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=32)),
                ('options', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(db_index=True)),
                ('exit_code', models.IntegerField()),
                ('succeeded', models.BooleanField()),
                ('summary', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-finished_at', '-id'],
            },
        ),
    ]
