# Generated by Django 6.1.1 on 2026-09-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginInfo',
            fields=[
                ('slug', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('found', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=300)),
                ('requires', models.CharField(blank=True, max_length=32)),
                ('tested', models.CharField(blank=True, max_length=32)),
                ('fetched_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteFetch',
            fields=[
                ('site_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('attempted_at', models.DateTimeField()),
                ('succeeded', models.BooleanField()),
                ('error', models.CharField(blank=True, max_length=500)),
                ('succeeded_at', models.DateTimeField(null=True)),
                ('wp_version', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SitePlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=32)),
                ('slug', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(max_length=16)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'slug'), name='unique_site_plugin')],
            },
        ),
    ]
